SET(CMAKE_SYSTEM_NAME QNX)

IF(NOT DEFINED ENV{QNX_TARGET})
  MESSAGE(FATAL_ERROR "Environment \"QNX_TARGET\" not defined")
ENDIF()

IF(NOT DEFINED ENV{QNX_HOST})
  MESSAGE(FATAL_ERROR "Environment \"QNX_HOST\" not defined")
ENDIF()

IF(NOT DEFINED ENV{QNX_ARCH})
  MESSAGE(FATAL_ERROR "Environment \"QNX_ARCH\" not defined, should one of x86, x86_64, aarch64le")
ENDIF()


SET(QNX_HOST $ENV{QNX_HOST})
SET(QNX_TARGET $ENV{QNX_TARGET})
SET(QNX_ARCH $ENV{QNX_ARCH})
SET(QCC_TARGET gcc_nto${QNX_ARCH}_gpp)

SET(CMAKE_C_COMPILER ${QNX_HOST}/usr/bin/qcc)
set(CMAKE_C_COMPILER_TARGET ${QCC_TARGET})
SET(CMAKE_C_FLAGS_DEBUG "-g")
SET(CMAKE_C_FLAGS_MINSIZEREL "-Os -DNDEBUG")
SET(CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG")
SET(CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g")

SET(CMAKE_CXX_COMPILER ${QNX_HOST}/usr/bin/qcc)
set(CMAKE_CXX_COMPILER_TARGET ${QCC_TARGET})
SET(CMAKE_CXX_FLAGS_DEBUG "-g")
SET(CMAKE_CXX_FLAGS_MINSIZEREL "-Os -DNDEBUG")
SET(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG")
SET(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g")

ADD_DEFINITIONS( -D__QNX__ )
ADD_DEFINITIONS( -D__QNXNTO__ )
ADD_DEFINITIONS( -D_QNX_SOURCE )
ADD_DEFINITIONS( -D__USE_ISOC99 )
ADD_DEFINITIONS( -D_GLIBCXX_USE_C99 )
